### PR TITLE
Sasha/osmosis update

### PR DESCRIPTION
**Pull request by sashas-lb**
integrating strato updates for osmosis

### CODE REVIEW

**Comment by muliby-lb** [comment]
How did you test it?

**Comment by sashas-lb** [comment]
locally it contains several fixes done by stratoscale that we are probably expiriencing in the lab

**Comment by muliby-lb** [comment]
The patches look good to my limited understanding of osmosis, but I am
curious how you checked it. I suggest full rootfs build cycle (you can
use my __version__ branch and bump the version to 1.01) with both
checkins and checkouts and then run it in the lab. If it looks fine,
ship it.

**Comment by george-lb** [comment]
still relevant? :-) 
can be closed?

**Comment by ira-lb** [comment]
how about we try this again, fresh? :)

**Pull request closed without merging**
